### ISSUE TITLE
Bagisto V2 support

### ISSUE THREAD

**Issue by haiderghaleb** [bagisto/bagisto-package-generator#24]
Any updates on when the generator will be for v2 especially the theme creation for the shop and admin?

**Comment by amit-webkul** [comment]
Hello @haiderghaleb,

We will release a new version of the package generator this week. Which supports Bagisto v2.

**Comment by haiderghaleb** [comment]
Hello @amit-webkul,

Perfect, thank you for the information.

Will the updated version include the creation of themes in the correct way not only the adding of the configuration in the themes.php e.g. creation of the configuration + the package?

 Also, I checked your PR and the creation of the shop theme and it's inside the shop key while the correct form is under themes key

**Comment by tmbenhura** [comment]
> Hello @haiderghaleb,
> 
> We will release a new version of the package generator this week. Which supports Bagisto v2.

Any update on this?

**Comment by ashishkumar-webkul** [comment]
@tmbenhura 

We are currently checking and testing package generator compatibility, we will update you ASAP. Be rest assure we will do it in this week.

Really Appreciated your patience.

Thanks

**Comment by jitendra-webkul** [comment]
This version is now supported with version 2

https://github.com/bagisto/bagisto-package-generator/releases/tag/v2.0.0
